#!/bin/bash

# Update the package index
echo "Updating, upgrading, and auto-removing packages in index..."
sudo apt upgrade -y
sudo apt update
sudo apt auto-remove -y

## Install Docker
echo "Installing Docker..."

# Add Docker's official GPG key
sudo apt install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |
  sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
sudo apt update

# Add Docker's stable repository
sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Creating docker group
if ! getent group docker >/dev/null; then
  sudo groupadd docker
fi

# Add your user to the Docker group
echo "Adding user to the Docker group..."
sudo usermod -aG docker $USER

# Enable docker to start on boot
sudo systemctl enable docker.service
sudo systemctl enable containerd.service

## Verify installations
echo "Verifying installations..."
docker --version
